const ENGLISH_LEVELS = {
  A1: [
    'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
    'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
    'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
    'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
    'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
    'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take',
    'people', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see',
    'other', 'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over',
    'think', 'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work',
    'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these',
    'give', 'day', 'most', 'us', 'hello', 'thank', 'please', 'yes', 'no',
    'big', 'small', 'hot', 'cold', 'good', 'bad', 'right', 'wrong', 'here',
    'where', 'when', 'why', 'how', 'what', 'who', 'this', 'that', 'water',
    'food', 'house', 'car', 'book', 'friend', 'family', 'mother', 'father'
  ],
  A2: [
    'thing', 'life', 'tell', 'boy', 'did', 'got', 'many', 'may', 'should',
    'too', 'right', 'still', 'great', 'old', 'own', 'same', 'big', 'place',
    'much', 'help', 'through', 'long', 'world', 'much', 'hand', 'high',
    'keep', 'last', 'let', 'city', 'tree', 'school', 'never', 'start',
    'city', 'earth', 'eye', 'light', 'thought', 'head', 'house', 'point',
    'today', 'while', 'always', 'often', 'sometimes', 'never', 'usually',
    'already', 'enough', 'however', 'another', 'nothing', 'everything',
    'between', 'since', 'without', 'under', 'before', 'above', 'below'
  ],
  B1: [
    'important', 'different', 'possible', 'remember', 'beautiful', 'experience',
    'problem', 'continue', 'example', 'change', 'believe', 'happen', 'provide',
    'support', 'produce', 'discover', 'appear', 'develop', 'consider', 'require',
    'suggest', 'increase', 'include', 'represent', 'affect', 'achieve',
    'approach', 'available', 'challenge', 'community', 'condition', 'consequence',
    'decision', 'demand', 'difference', 'doubt', 'encourage', 'establish',
    'event', 'evidence', 'exchange', 'exist', 'explain', 'factor', 'finally',
    'focus', 'form', 'function', 'identify', 'imagine', 'impact', 'improve',
    'influence', 'involve', 'lead', 'manage', 'meaning', 'method', 'occur',
    'opportunity', 'particular', 'period', 'perspective', 'physical', 'plan',
    'position', 'process', 'purpose', 'question', 'realize', 'reason', 'receive',
    'recognize', 'reduce', 'relationship', 'remove', 'response', 'result',
    'reveal', 'role', 'select', 'significant', 'similar', 'situation', 'social',
    'structure', 'subject', 'succeed', 'suggest', 'support', 'technology',
    'tend', 'therefore', 'threat', 'variety', 'vehicle', 'view', 'volume'
  ],
  B2: [
    'abstract', 'accomplish', 'accumulate', 'accurate', 'acknowledge', 'acquire',
    'adapt', 'adequate', 'adjust', 'administration', 'adopt', 'advance',
    'advantage', 'advocate', 'afford', 'agenda', 'aggressive', 'allocate',
    'ambiguous', 'ambitious', 'amend', 'anticipate', 'apparent', 'appetite',
    'appreciable', 'appropriate', 'arbitrary', 'assess', 'assign', 'assist',
    'assume', 'authentic', 'authority', 'automatic', 'aware', 'awkward',
    'backdrop', 'barely', 'barrier', 'bias', 'binding', 'blanket', 'blast',
    'blaze', 'bleak', 'blend', 'block', 'boost', 'bound', 'breach', 'brief',
    'broad', 'browse', 'brutal', 'bulk', 'bulletin', 'burden', 'bureaucracy',
    'capable', 'capacity', 'capture', 'casual', 'cease', 'census', 'ceremony',
    'champion', 'chaos', 'characteristic', 'charter', 'chronic', 'circulate',
    'circumstance', 'cite', 'civic', 'civilian', 'clarify', 'cleanse', 'climate',
    'clone', 'cluster', 'coherent', 'coincide', 'collaborate', 'collapse',
    'colleague', 'collision', 'combat', 'combine', 'commentary', 'commission',
    'commit', 'commodity', 'communist', 'compact', 'companion', 'comparison',
    'compel', 'compensate', 'competent', 'compile', 'complement', 'complex',
    'complicated', 'component', 'compose', 'comprehensive', 'comprise', 'compromise',
    'compulsory', 'conceive', 'concentrate', 'concept', 'concern', 'conclude',
    'concrete', 'condemn', 'conduct', 'confess', 'confidence', 'confine',
    'confirm', 'conflict', 'confront', 'congress', 'conscience', 'conscious',
    'consensus', 'consent', 'consequence', 'conservative', 'considerable',
    'consist', 'consistent', 'constant', 'constitute', 'construct', 'consult',
    'consume', 'contemporary', 'contend', 'context', 'contract', 'contradict',
    'contrast', 'contribute', 'controversial', 'convention', 'convert',
    'convince', 'cooperate', 'coordinate', 'corporate', 'correspond', 'corrupt',
    'counsel', 'coverage', 'craft', 'crash', 'credential', 'criterion',
    'critical', 'crucial', 'crude', 'cumulative', 'currency', 'curriculum',
    'custom', 'database', 'deadline', 'debate', 'decade', 'decent', 'decline',
    'decorate', 'decrease', 'dedicate', 'defeat', 'defend', 'deficit', 'define',
    'definite', 'deliberate', 'delicate', 'democracy', 'demonstrate', 'deny',
    'department', 'dependent', 'deposit', 'deprive', 'derive', 'describe',
    'designate', 'desire', 'desperate', 'despite', 'destination', 'destroy',
    'detail', 'detect', 'determine', 'devote', 'dimension', 'diminish',
    'diplomacy', 'disappoint', 'disaster', 'discipline', 'disclose', 'discount',
    'discrete', 'discrimination', 'disposal', 'dispose', 'dispute', 'dissolve',
    'distinct', 'distinguish', 'distribute', 'disturb', 'diverse', 'diversity',
    'document', 'domestic', 'dominant', 'donate', 'dose', 'draft', 'drama',
    'drift', 'durable', 'duration', 'dynamic', 'eager', 'economy', 'editorial',
    'elaborate', 'elegant', 'element', 'eliminate', 'embrace', 'emerge',
    'emergency', 'emission', 'emphasis', 'empire', 'encounter', 'encourage',
    'engage', 'enormous', 'enterprise', 'enthusiasm', 'entity', 'entrepreneur',
    'envelope', 'equality', 'equip', 'equivalent', 'era', 'error', 'essence',
    'establish', 'estate', 'ethical', 'ethnic', 'evaluate', 'eventually',
    'evidence', 'evil', 'evolution', 'evolve', 'exceed', 'exception',
    'excess', 'exclude', 'exclusive', 'execute', 'executive', 'exempt',
    'exercise', 'exhibit', 'exile', 'expand', 'expansion', 'expedition',
    'expense', 'experimental', 'expertise', 'explicit', 'exploit', 'explosion',
    'export', 'expose', 'exposure', 'extend', 'extensive', 'extent',
    'external', 'extract', 'extraordinary', 'extreme', 'fabric', 'facilitate',
    'faculty', 'fashion', 'fatigue', 'fault', 'feasible', 'feature', 'federal',
    'fee', 'fellow', 'feminine', 'fierce', 'figure', 'file', 'finance',
    'finding', 'firm', 'flag', 'flaw', 'flesh', 'flexible', 'float',
    'flourish', 'fluctuate', 'folk', 'forecast', 'format', 'former', 'formula',
    'forth', 'fortune', 'fossil', 'fraction', 'fragment', 'framework', 'frequent',
    'frontier', 'frustrate', 'fulfill', 'fund', 'fundamental', 'furnish',
    'gallery', 'gather', 'gaze', 'gender', 'gene', 'generate', 'generous',
    'genius', 'genuine', 'gesture', 'global', 'govern', 'grace', 'grade',
    'gradually', 'grant', 'graphic', 'grateful', 'grave', 'grind', 'grip',
    'gross', 'guarantee', 'guardian', 'guideline', 'guitar', 'gut', 'habitat',
    'halt', 'harsh', 'harvest', 'heading', 'heal', 'heap', 'heritage',
    'hierarchy', 'highlight', 'horizon', 'horror', 'hostile', 'humble',
    'hypothesis', 'icon', 'ideology', 'ignore', 'illustrate', 'image',
    'immense', 'immigrant', 'immune', 'implement', 'implication', 'implicit',
    'impose', 'impress', 'impulse', 'inadequate', 'incentive', 'incidence',
    'incline', 'incorporate', 'incredible', 'incur', 'indicate', 'indigenous',
    'individual', 'inevitable', 'infant', 'inflation', 'infrastructure',
    'ingredient', 'inhabit', 'inherit', 'initial', 'initiate', 'innocent',
    'innovation', 'input', 'insert', 'insight', 'inspect', 'inspiration',
    'install', 'instance', 'instant', 'instinct', 'institution', 'integrate',
    'intellectual', 'intelligent', 'intense', 'interact', 'interference',
    'internal', 'interpret', 'interval', 'intimate', 'invasion', 'invest',
    'investigate', 'investment', 'invisible', 'involve', 'irony', 'isolate',
    'justify', 'keen', 'label', 'labor', 'landscape', 'launch', 'lawsuit',
    'layout', 'leadership', 'lean', 'lecture', 'legend', 'legislation',
    'legitimate', 'leisure', 'lend', 'lesson', 'liberal', 'liberty', 'license',
    'lifetime', 'likewise', 'linear', 'linguistic', 'literary', 'locate',
    'logic', 'longitude', 'loyalty', 'lure', 'luxury', 'magnitude', 'mainstream',
    'maintain', 'majority', 'manifest', 'manipulate', 'manuscript', 'margin',
    'marine', 'marketplace', 'massive', 'mate', 'mature', 'maximum', 'mechanism',
    'medieval', 'membrane', 'mercy', 'mere', 'merely', 'merger', 'methodology',
    'middle', 'migrate', 'milestone', 'military', 'mineral', 'minimum', 'minister',
    'minor', 'minority', 'moderate', 'modify', 'momentum', 'monopoly', 'moral',
    'moreover', 'mortgage', 'motion', 'motivate', 'mount', 'multiple',
    'multiply', 'municipal', 'mutual', 'myth', 'naked', 'narrative', 'negative',
    'neglect', 'negotiate', 'nerve', 'nevertheless', 'noble', 'nod',
    'nominal', 'nonetheless', 'norm', 'notable', 'notion', 'novel',
    'nuclear', 'numerous', 'nurture', 'obey', 'object', 'objective',
    'obligation', 'observe', 'obtain', 'obvious', 'occasion', 'occupation',
    'occupy', 'odd', 'offend', 'offset', 'offspring', 'ongoing', 'opening',
    'operate', 'opponent', 'oppose', 'opposite', 'opt', 'optimistic',
    'option', 'orbit', 'organic', 'orient', 'origin', 'outcome', 'output',
    'outrage', 'overcome', 'overlook', 'overseas', 'overtake', 'overview',
    'owing', 'pace', 'pack', 'pact', 'palm', 'panel', 'panic', 'parallel',
    'parameter', 'participation', 'particular', 'patent', 'patience', 'pause',
    'peak', 'peer', 'penalty', 'perceive', 'persist', 'personnel', 'perspective',
    'phase', 'phenomenon', 'philosophy', 'pioneer', 'pipeline', 'platform',
    'plea', 'plead', 'pledge', 'plot', 'plug', 'plunge', 'pocket',
    'poetry', 'polar', 'poll', 'pollution', 'pond', 'pool', 'popularity',
    'portion', 'portrait', 'pose', 'possess', 'postpone', 'potential',
    'practitioner', 'precede', 'precise', 'predict', 'predominantly', 'preference',
    'prejudice', 'preliminary', 'premise', 'premium', 'prescribe', 'presence',
    'presentation', 'preserve', 'presidency', 'presume', 'prevail', 'prevalent',
    'prevent', 'previous', 'primarily', 'prime', 'principal', 'principle',
    'prior', 'priority', 'privilege', 'proceed', 'professional', 'profile',
    'prohibit', 'project', 'prominent', 'promote', 'prompt', 'propaganda',
    'proportion', 'proposal', 'propose', 'prosecute', 'prospect', 'prosperity',
    'protocol', 'provider', 'province', 'provision', 'provoke', 'publication',
    'pursue', 'puzzle', 'qualify', 'quantitative', 'quarter', 'quote',
    'radical', 'rage', 'raid', 'rally', 'random', 'range', 'rapid',
    'rare', 'ratio', 'rational', 'raw', 'realm', 'rear', 'reasonable',
    'receipt', 'recover', 'reform', 'regime', 'region', 'register', 'regulate',
    'reinforce', 'reject', 'relevant', 'reluctant', 'rely', 'remark',
    'remedy', 'render', 'renew', 'republic', 'reputation', 'request',
    'require', 'research', 'resent', 'reserve', 'reside', 'resign', 'resist',
    'resolution', 'resolve', 'resort', 'resource', 'respond', 'restore',
    'restrict', 'retain', 'retire', 'retrieve', 'reveal', 'revenue', 'reverse',
    'revise', 'revolution', 'rhetoric', 'ridiculous', 'rigid', 'rival',
    'robust', 'romantic', 'route', 'routine', 'sacrifice', 'sample',
    'sanction', 'satellite', 'satisfy', 'scale', 'scandal', 'scare',
    'scenario', 'scheme', 'scope', 'scratch', 'sector', 'segment',
    'select', 'semester', 'seminar', 'senate', 'senior', 'sensation',
    'sensitive', 'sentence', 'separate', 'sequence', 'serial', 'series',
    'setback', 'severe', 'shelter', 'shift', 'shrink', 'signal', 'significance',
    'simulate', 'simultaneous', 'skeptical', 'slavery', 'slide', 'slim',
    'slip', 'slope', 'smart', 'snap', 'soar', 'sole', 'solely',
    'solemn', 'solidarity', 'sophisticated', 'sovereign', 'span', 'spark',
    'speculate', 'sphere', 'spirit', 'sponsor', 'spot', 'spread', 'squeeze',
    'stab', 'stability', 'stable', 'stance', 'standpoint', 'statute',
    'steady', 'steep', 'stem', 'stimulus', 'stir', 'strain', 'strategic',
    'strengthen', 'stress', 'stride', 'strip', 'strive', 'stroke',
    'structural', 'submit', 'subordinate', 'subscribe', 'subsequent', 'subsidy',
    'substance', 'substantial', 'substitute', 'succession', 'successive',
    'sue', 'summit', 'superficial', 'supplement', 'supply', 'support',
    'supreme', 'surplus', 'surrender', 'surround', 'survey', 'survival',
    'survive', 'suspect', 'suspend', 'sustain', 'swallow', 'swear', 'swing',
    'switch', 'symbol', 'sympathy', 'symptom', 'syndrome', 'tackle',
    'tail', 'talent', 'target', 'tariff', 'tax', 'tear', 'technique',
    'technology', 'temporary', 'tender', 'tenure', 'terminal', 'terminate',
    'terrific', 'territory', 'terror', 'textile', 'theme', 'theoretical',
    'therapy', 'thereby', 'thesis', 'thorough', 'threat', 'threshold',
    'thrill', 'thrive', 'tide', 'tight', 'tilt', 'tip', 'tissue',
    'title', 'tolerance', 'toll', 'tone', 'topic', 'tough', 'tourism',
    'toxic', 'trace', 'track', 'trail', 'trait', 'transaction', 'transform',
    'transformation', 'transition', 'transmit', 'transport', 'trap',
    'treaty', 'tremendous', 'trend', 'trial', 'tribute', 'trigger',
    'triumph', 'troop', 'tropical', 'trust', 'tube', 'tune', 'twist',
    'ultimate', 'undergo', 'underlie', 'undertake', 'unemployment', 'unfold',
    'unfortunately', 'unify', 'unique', 'unite', 'unity', 'universal',
    'update', 'uphold', 'upper', 'urban', 'urge', 'utility', 'utilize',
    'utmost', 'vacant', 'vacuum', 'vague', 'valid', 'value', 'vanish',
    'variable', 'variance', 'variation', 'vast', 'vehicle', 'venture',
    'version', 'veteran', 'via', 'victim', 'victory', 'violence', 'virtual',
    'visible', 'vision', 'vital', 'vivid', 'vocal', 'volume', 'voluntary',
    'volunteer', 'vote', 'vulnerability', 'wage', 'wander', 'warn',
    'warrant', 'wealth', 'weapon', 'weave', 'weird', 'welfare', 'whereas',
    'whisper', 'wholesale', 'widespread', 'wildlife', 'witness', 'workforce',
    'workshop', 'worship', 'worthwhile', 'yield', 'zone'
  ],
  C1: [
    'aberration', 'abhor', 'abjure', 'abnegate', 'abrogate', 'abscond',
    'absolve', 'abstain', 'accolade', 'acquiesce', 'acumen', 'adamant',
    'adept', 'admonish', 'adroit', 'adulation', 'adversity', 'aesthetic',
    'affable', 'aggrandize', 'alacrity', 'allege', 'altruism', 'amalgamate',
    'ambivalent', 'ameliorate', 'amiable', 'amorphous', 'anachronism',
    'analogous', 'anecdote', 'anomaly', 'antagonize', 'antecedent', 'anthology',
    'apathy', 'aplomb', 'apocryphal', 'appease', 'approbation', 'archaic',
    'arduous', 'articulate', 'ascetic', 'assiduous', 'astute', 'atone',
    'audacious', 'austere', 'autonomous', 'aver', 'aversion', 'avid',
    'banal', 'bane', 'bastion', 'belligerent', 'benevolent', 'berate',
    'bereft', 'beseech', 'bizarre', 'bolster', 'bombastic', 'bourgeois',
    'brazen', 'brevity', 'bucolic', 'bulwark', 'burgeon', 'burnish',
    'buttress', 'cacophony', 'cajole', 'callous', 'candor', 'canny',
    'capitulate', 'capricious', 'castigate', 'catalyst', 'caustic',
    'cavalier', 'censure', 'chicanery', 'circumscribe', 'circumvent',
    'clandestine', 'clemency', 'coalesce', 'cogent', 'commensurate',
    'compendium', 'complacent', 'compliant', 'concede', 'conciliatory',
    'condone', 'confound', 'congenial', 'conjecture', 'connoisseur',
    'consecrate', 'consonant', 'construe', 'consummate', 'contend',
    'contentious', 'contrite', 'conundrum', 'convivial', 'copious',
    'cordial', 'corroborate', 'countenance', 'countervail', 'coup',
    'credulous', 'culminate', 'cupidity', 'curtail', 'cynical', 'dearth',
    'debacle', 'debilitate', 'decrepit', 'deference', 'defunct', 'deify',
    'deign', 'deleterious', 'deliberation', 'delineate', 'demagogue',
    'demure', 'denigrate', 'deprecate', 'deride', 'despondent', 'despot',
    'destitute', 'deter', 'detrimental', 'devious', 'devolve', 'diatribe',
    'didactic', 'diffident', 'digress', 'dilatory', 'dilettante',
    'diminutive', 'disaffected', 'disapprobation', 'disarray', 'discern',
    'disconcert', 'disdain', 'disenfranchise', 'disparage', 'disparate',
    'disseminate', 'dissipate', 'docile', 'dolor', 'duplicity', 'dwarf',
    'ebullient', 'eclectic', 'effervescent', 'efficacious', 'effrontery',
    'egalitarian', 'egregious', 'elicit', 'eloquent', 'elucidate',
    'elusive', 'emaciated', 'emanate', 'embellish', 'eminent', 'empathy',
    'empirical', 'emulate', 'endeavor', 'ennui', 'ephemeral', 'epitome',
    'equate', 'equanimity', 'equivocal', 'eradicate', 'erratic', 'erudite',
    'esoteric', 'espouse', 'eulogize', 'euphemism', 'exasperate',
    'exemplary', 'exemplify', 'exhort', 'exonerate', 'expedient',
    'exploitative', 'expunge', 'extol', 'extraneous', 'extravagant',
    'facetious', 'fallacious', 'fathom', 'fatuous', 'fecund', 'fervent',
    'fickle', 'fidelity', 'flagrant', 'flippant', 'florid', 'flout',
    'foment', 'forbearance', 'forestall', 'fortuitous', 'fractious',
    'frivolous', 'frugal', 'futile', 'gainsay', 'galvanize', 'garrulous',
    'gratuitous', 'gregarious', 'hackneyed', 'hamper', 'hapless',
    'harangue', 'harbinger', 'hegemony', 'heresy', 'hermetic', 'heterodox',
    'histrionic', 'homogeneous', 'hyperbole', 'iconoclast', 'idiosyncratic',
    'ignominious', 'immutable', 'impasse', 'impeccable', 'impede',
    'imperious', 'imperturbable', 'impervious', 'implacable', 'implicit',
    'importune', 'impregnable', 'impromptu', 'impugn', 'inadvertent',
    'incandescent', 'incendiary', 'incisive', 'inclement', 'incongruous',
    'incontrovertible', 'incorrigible', 'incredulous', 'indelible',
    'indemnify', 'indict', 'indifferent', 'indigenous', 'indignant',
    'indomitable', 'indulgent', 'ineffable', 'ineluctable', 'inept',
    'inexorable', 'infallible', 'infamous', 'infectious', 'inference',
    'inflammatory', 'inimical', 'innate', 'innocuous', 'inscrutable',
    'insidious', 'insipid', 'insolent', 'insouciant', 'intransigent',
    'intrepid', 'intrinsic', 'inundate', 'invective', 'inveterate',
    'irascible', 'irksome', 'irreverent', 'itinerant', 'jubilant',
    'judicious', 'juxtapose', 'laconic', 'languid', 'lapsarian',
    'largesse', 'laudatory', 'lavish', 'lethargic', 'levity', 'loquacious',
    'lugubrious', 'luminous', 'magnanimous', 'malfeasance', 'malleable',
    'meander', 'meddle', 'melancholy', 'mendacious', 'mercenary',
    'mercurial', 'meticulous', 'milieu', 'misanthrope', 'miserly',
    'mitigate', 'mollify', 'moratorium', 'moribund', 'multifaceted',
    'munificent', 'myopic', 'nefarious', 'negligent', 'neophyte',
    'nihilism', 'nobility', 'nonchalant', 'nuance', 'obdurate',
    'obfuscate', 'oblique', 'oblivious', 'obscure', 'obsequious',
    'obstreperous', 'obtuse', 'obviate', 'omnipotent', 'onerous',
    'opaque', 'opprobrium', 'ornate', 'orthodox', 'ostensible',
    'ostentatious', 'pacify', 'palatable', 'palliate', 'panacea',
    'paradigm', 'paragon', 'parochial', 'parsimonious', 'partisan',
    'patronize', 'paucity', 'pedantic', 'penchant', 'penitent',
    'perfunctory', 'peripatetic', 'pernicious', 'perpetuate', 'perquisite',
    'pertinent', 'peruse', 'pestilent', 'philanthropy', 'phlegmatic',
    'placate', 'platitude', 'plausible', 'plenipotentiary', 'plethora',
    'pontificate', 'portentous', 'pragmatic', 'prattle', 'precarious',
    'precedent', 'precipitate', 'precocious', 'predilection', 'presage',
    'prescient', 'presumptuous', 'prevalent', 'pristine', 'probity',
    'proclivity', 'prodigal', 'profound', 'profuse', 'prohibitive',
    'proletariat', 'propensity', 'propitious', 'propriety', 'prosaic',
    'proscribe', 'proselytize', 'protean', 'provenance', 'provocative',
    'prudent', 'pugnacious', 'punctilious', 'pundit', 'pungent',
    'pursuant', 'pusillanimous', 'quagmire', 'quandary', 'querulous',
    'quiescent', 'quintessential', 'raconteur', 'rancor', 'rapacious',
    'raucous', 'recalcitrant', 'recant', 'reciprocate', 'recluse',
    'rectitude', 'redolent', 'refute', 'rejuvenate', 'relegate',
    'remorse', 'renounce', 'replete', 'reprehensible', 'repudiate',
    'requisite', 'rescind', 'resilient', 'resplendent', 'restitution',
    'reticent', 'revere', 'ribald', 'rife', 'risible', 'robust',
    'sagacious', 'salacious', 'sanguine', 'sardonic', 'scrupulous',
    'sedulous', 'sententious', 'serendipity', 'servile', 'solicitous',
    'soporific', 'specious', 'spurious', 'staid', 'steadfast',
    'stoic', 'strident', 'subjugate', 'sublime', 'substantiate',
    'succinct', 'suffocate', 'superfluous', 'supplant', 'suppliant',
    'supremacy', 'surreptitious', 'sycophant', 'sylvan', 'taciturn',
    'tangential', 'tantamount', 'temerity', 'temperate', 'tenacious',
    'tenet', 'tepid', 'terse', 'timorous', 'torpid', 'tractable',
    'transient', 'trepidation', 'truculent', 'turgid', 'tutelage',
    'umbrage', 'unconscionable', 'unctuous', 'undulating', 'unequivocal',
    'unimpeachable', 'untenable', 'upbraid', 'usurp', 'utilitarian',
    'vacillate', 'valediction', 'vapid', 'vehement', 'venerate',
    'veracity', 'verbose', 'verdant', 'vestige', 'vicarious',
    'vindicate', 'virulent', 'visceral', 'vitriolic', 'vociferous',
    'voluble', 'voracious', 'vulnerable', 'wanton', 'whimsical',
    'winsome', 'wistful', 'zealous'
  ],
  C2: [
    'abdicate', 'abeyance', 'ablution', 'abnegation', 'abstemious',
    'acarpous', 'acerbic', 'acquisitive', 'actuate', 'adjudicate',
    'adumbrate', 'aegis', 'affectation', 'agglomerate', 'agnostic',
    'agrarian', 'alchemy', 'allegory', 'alluvial', 'amalgam',
    'amalgamate', 'ameliorate', 'anathema', 'animus', 'anneal',
    'antediluvian', 'anthropomorphize', 'antipathy', 'aperture',
    'apothegm', 'apotheosis', 'appellation', 'approbation', 'arabesque',
    'arcane', 'archipelago', 'arduous', 'armistice', 'ascendancy',
    'asperity', 'asseverate', 'assuage', 'attenuate', 'augment',
    'aureole', 'auspicious', 'autarky', 'autodidact', 'avarice',
    'axiomatic', 'badinage', 'balustrade', 'beatific', 'bellwether',
    'beneficent', 'blandishment', 'boorish', 'borborygmus', 'brachiate',
    'bravura', 'brio', 'brouhaha', 'bulwark', 'bumptious',
    'cabal', 'cadence', 'calumny', 'canard', 'captious',
    'cardinal', 'carnal', 'carnivorous', 'casuistry', 'catharsis',
    'causality', 'caveat', 'celerity', 'censorious', 'cerulean',
    'chagrin', 'chimera', 'chivalry', 'churlish', 'circuitous',
    'circumlocution', 'circumnavigate', 'clairvoyant', 'clement',
    'clerisy', 'codify', 'colloquial', 'comestible', 'comity',
    'compendious', 'complaisant', 'comport', 'concatenate', 'conciliatory',
    'concomitant', 'conflagration', 'confluence', 'congenital',
    'connive', 'connoisseurship', 'consecrate', 'consanguinity',
    'contiguous', 'contumacious', 'contumely', 'conviviality',
    'coruscate', 'cosmopolitan', 'countermand', 'countervailing',
    'crepuscular', 'crucible', 'culminate', 'culpable', 'cupidity',
    'curmudgeon', 'cynosure', 'decadence', 'decamp', 'decrepitude',
    'defenestrate', 'defoliate', 'deglutition', 'degust', 'delectation',
    'delineation', 'demagogic', 'demarcation', 'demotic', 'denouement',
    'depredation', 'deracinate', 'derisory', 'desiccate', 'desultory',
    'diaphanous', 'dichotomy', 'didacticism', 'diffidence', 'digression',
    'dilatory', 'diminution', 'disabuse', 'disaffected', 'disapprobation',
    'discomfiture', 'discombobulate', 'discordant', 'discreet', 'disdain',
    'disquisition', 'dissemble', 'dissident', 'distillation', 'divergent',
    'divulgate', 'dolorous', 'doppelganger', 'doughty', 'dubitante',
    'ebullience', 'ecumenical', 'edification', 'efflorescence',
    'effrontery', 'effulgent', 'egalitarianism', 'egomania', 'egregious',
    'eleemosynary', 'elogium', 'emaciate', 'embrocation', 'emollient',
    'emolument', 'empyrean', 'endemic', 'encomium', 'endue',
    'enfilade', 'engender', 'enigmatic', 'ennoble', 'enormity',
    'ensconced', 'enthrall', 'ephemeron', 'epigram', 'epiphenomenon',
    'epistemology', 'equanimous', 'equivocate', 'eremite', 'ergo',
    'eristical', 'eschatology', 'esotericism', 'ethereal', 'etiology',
    'evanescent', 'eviscerate', 'excoriate', 'excursus', 'execrable',
    'exegesis', 'exiguous', 'exonerate', 'expatiate', 'expediency',
    'explicable', 'explicate', 'expostulate', 'expropriate', 'exscind',
    'extemporaneous', 'extirpate', 'extricate', 'exude', 'facile',
    'facsimile', 'factotum', 'faineant', 'fait accompli', 'fanfaronade',
    'farinaceous', 'febrile', 'feckless', 'felicitous', 'felo de se',
    'fenestration', 'feral', 'feracious', 'fiduciary', 'filigree',
    'flail', 'flamboyant', 'fleshly', 'flibbertigibbet', 'flotsam',
    'foppish', 'forswear', 'fortuitism', 'fracas', 'froward',
    'fulminate', 'fulsome', 'fungible', 'fusillade', 'gainsay',
    'gambit', 'gauche', 'genuflect', 'germane', 'gerrymander',
    'glabrous', 'gladiatorial', 'glimmer', 'gratuitous', 'gravitas',
    'gregariousness', 'grisly', 'guerrilla', 'haberdashery', 'habitus',
    'hagiography', 'harlequin', 'hebdomadal', 'hedonism', 'hegemonic',
    'heliolatrous', 'hemidemisemiquaver', 'hendiadys', 'hermeneutics',
    'heterodox', 'heterogeneous', 'heuristic', 'hirsute', 'hoarfrost',
    'hobbesian', 'homiletic', 'homologous', 'homozygous', 'houri',
    'huckster', 'hymeneal', 'hypostasis', 'ichthyic', 'iconoclasm',
    'ignominy', 'imbricate', 'imbroglio', 'immanence', 'impecunious',
    'imperatorial', 'imperiousness', 'imperturbability', 'impiety',
    'imponderable', 'imprecation', 'imprimatur', 'improvident', 'impunity',
    'inchoate', 'incogitant', 'incommensurate', 'incommunicado',
    'inconsequent', 'incorporeal', 'incorruptible', 'incubus', 'indelible',
    'indicative', 'indicia', 'indigence', 'indiscerptible', 'indolence',
    'indomitable', 'ineffable', 'ineffaceable', 'ineluctable', 'inexorable',
    'infelicitous', 'ingenious', 'ingenuous', 'inimitable', 'insensate',
    'insouciance', 'intransigence', 'internecine', 'intractable', 'invincible',
    'irascibility', 'irredentist', 'itinerancy', 'jactitation', 'jejune',
    'jingoism', 'judicature', 'jurisprudence', 'juvenescence', 'kairos',
    'kenosis', 'kismet', 'kowtow', 'labefactation', 'labyrinthine',
    'lachrymose', 'lagniappe', 'lambaste', 'lambent', 'lang Syne',
    'lapsus linguae', 'lascivious', 'lassitude', 'lateral', 'lattice',
    'lectionary', 'legerdemain', 'lexicography', 'lexis', 'libertine',
    'licentiate', 'liminal', 'litany', 'litigious', 'logorrhea',
    'longueur', 'loquacity', 'lugubriousness', 'lustration', 'machination',
    'magniloquent', 'maieutic', 'malleable', 'mammonism', 'manacle',
    'manifestation', 'manumission', 'marginalia', 'marplot', 'maudlin',
    'mawkish', 'meliorism', 'membranous', 'meretricious', 'meritorious',
    'metonymy', 'miasma', 'militate', 'millenarian', 'miscreant',
    'misfeasance', 'misanthropy', 'moue', 'multitudinous', 'munificence',
    'nascent', 'nebulous', 'necromancy', 'necrosis', 'nemesis',
    'nescient', 'nihilistic', 'nimiety', 'nirvana', 'noblesse oblige',
    'nonpareil', 'nympholept', 'obdurateness', 'obeisance', 'obelisk',
    'obeah', 'objurgation', 'obloquy', 'obsequiousness', 'obstreperousness',
    'obtuseness', 'obviation', 'oligarchy', 'omniscient', 'onomatopoeia',
    'opprobrious', 'orgiastic', 'orthopraxy', 'ossify', 'ostracize',
    'overweening', 'oxymoron', 'pabulum', 'paean', 'palimpsest',
    'palinode', 'palliation', 'panegyric', 'panopticon', 'pantheism',
    'parable', 'paradisiacal', 'paralipsis', 'paramount', 'paraphernalia',
    'parasol', 'parsimoniousness', 'parturition', 'pasquinade', 'pathos',
    'patriarchal', 'pauciloquy', 'peculation', 'pecuniary', 'pedagogics',
    'penumbra', 'perambulate', 'percipient', 'perdition', 'perfidious',
    'periphrasis', 'peroration', 'perseverate', 'perspicacious', 'pertinacious',
    'pestiferous', 'pettifogging', 'phantasmagoria', 'philippic', 'physiognomy',
    'picayune', 'pied', 'picaresque', 'piffle', 'pinnace',
    'pious', 'plangent', 'pleonasm', 'plutocracy', 'polemic',
    'polyphony', 'portmanteau', 'positivism', 'postprandial', 'potentate',
    'poultice', 'praxis', 'precession', 'precipitous', 'preceptor',
    'precipitancy', 'predicate', 'preeminent', 'prehensile', 'prelude',
    'preponderance', 'prevaricate', 'proboscis', 'proclivity', 'procrustean',
    'prodigy', 'profligacy', 'promethean', 'promiscuous', 'propinquity',
    'proselyte', 'prostration', 'provenance', 'proviso', 'punctilio',
    'purview', 'pusillanimity', 'quiddity', 'quiescence', 'quietude',
    'quintessence', 'quixotic', 'quotidian', 'raconteur', 'raillery',
    'ramification', 'rapport', 'rapprochement', 'recalcitrance', 'recapitulate',
    'recidivism', 'recondite', 'recrimination', 'rectitude', 'redoubtable',
    'refractory', 'refulgent', 'regimen', 'remonstrance', 'remunerative',
    'renascent', 'replevin', 'reprobate', 'requiem', 'rescission',
    'residuum', 'retrenchment', 'ribaldry', 'risibility', 'rogue',
    'rubicon', 'sacerdotal', 'salubrious', 'sanctimonious', 'sanguinary',
    'sapid', 'saturnine', 'scintilla', 'sedition', 'seditious',
    'sepulchral', 'sesquipedalian', 'sinuous', 'sobriquet', 'soliloquy',
    'sombre', 'somnolent', 'sophistry', 'speculative', 'stochastic',
    'stolid', 'stratagem', 'stultify', 'subaltern', 'suborn',
    'sui generis', 'sumptuary', 'supercilious', 'supernumerary', 'supplicate',
    'susurrant', 'susurrus', 'syllogism', 'symphony', 'synecdoche',
    'tableau', 'tautological', 'taxonomy', 'tedium', 'teleological',
    'temerarious', 'temporize', 'tendentious', 'tergiversate', 'terminus ad quem',
    'tessellation', 'tirade', 'torpor', 'totalitarian', 'transcendental',
    'transmigration', 'trenchant', 'tryst', 'turbid', 'tutelary',
    'ultramontane', 'unconscionable', 'unctuousness', 'undefiled', 'underivative',
    'unilateral', 'usury', 'uxorious', 'vacuousness', 'valedictory',
    'variegated', 'vehemence', 'vendible', 'veneer', 'veracity',
    'verdure', 'veridical', 'vernacular', 'versimilar', 'vespertine',
    'vexatious', 'vicissitude', 'virago', 'viridity', 'vivacious',
    'vivisection', 'vocable', 'volition', 'voluminous', 'vortices',
    'weltanschauung', 'wunderkind', 'xenophobia', 'zeitgeist', 'zenith',
    'zephyr'
  ]
};

export class LevelClassifier {
  #wordLists;

  constructor() {
    this.#wordLists = ENGLISH_LEVELS;
  }

  classify(word) {
    const lower = word.toLowerCase().trim();

    for (const [level, words] of Object.entries(this.#wordLists)) {
      if (words.includes(lower)) return level;
    }

    if (lower.length <= 4) return 'A1';
    if (lower.length <= 6) return 'A2';
    if (lower.length <= 8) return 'B1';
    if (lower.length <= 10) return 'B2';

    const syllables = this.#countSyllables(lower);
    if (syllables <= 2) return 'B1';
    if (syllables <= 3) return 'B2';
    if (syllables <= 4) return 'C1';
    return 'C2';
  }

  #countSyllables(word) {
    word = word.toLowerCase();
    if (word.length <= 3) return 1;
    word = word.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/, '');
    word = word.replace(/^y/, '');
    const matches = word.match(/[aeiouy]{1,2}/g);
    return matches ? matches.length : 1;
  }

  getLevelDescription(level) {
    const descriptions = {
      'A1': 'Principiante - Palabras muy comunes del día a día',
      'A2': 'Básico - Vocabulario cotidiano y familiar',
      'B1': 'Intermedio - Temas personales y profesionales',
      'B2': 'Intermedio alto - Textos complejos y abstractos',
      'C1': 'Avanzado - Lenguaje sofisticado y especializado',
      'C2': 'Master - Vocabulario académico y literario'
    };
    return descriptions[level] || 'Nivel desconocido';
  }

  getLevelColor(level) {
    const colors = {
      'A1': '#4CAF50',
      'A2': '#8BC34A',
      'B1': '#FFC107',
      'B2': '#FF9800',
      'C1': '#F44336',
      'C2': '#9C27B0'
    };
    return colors[level] || '#757575';
  }
}
