export const Messages = {
  TRANSLATE_WORD: 'TRANSLATE_WORD',
  WORD_SAVED: 'WORD_SAVED',
  WORD_DELETED: 'WORD_DELETED',
  GET_HISTORY: 'GET_HISTORY',
  GET_WORD: 'GET_WORD',
  GET_STATS: 'GET_STATS',
  CALCULATE_REVIEW: 'CALCULATE_REVIEW',
  TOGGLE_WIDGET: 'TOGGLE_WIDGET',
  WORD_CAPTURED: 'WORD_CAPTURED',
  ERROR: 'ERROR',
  SUCCESS: 'SUCCESS',
};
